# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
