# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20171227_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='surname',
            new_name='last_name',
        ),
    ]
