# Generated by Django 2.0 on 2018-01-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_recipebook_image'),
        ('profiles', '0006_profile_searches'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='recipes',
            field=models.ManyToManyField(to='food.Recipe'),
        ),
    ]
