# Generated by Django 2.0 on 2018-01-04 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='recetario',
            new_name='recipe_book',
        ),
    ]
