# Generated by Django 2.0 on 2018-01-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20180104_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredient',
            old_name='text',
            new_name='name',
        ),
    ]
