# Generated by Django 2.0 on 2018-01-06 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
