# Generated by Django 2.0 on 2018-01-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0005_auto_20180106_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
